# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SDFIlt4wvSZ72WzAqsXW5E31BraqnO_g
"""

from google.colab import drive
drive.mount('/content/drive')

cd drive

cd My Drive

cd Project

pwd

!pip install python-mnist

import cv2
import numpy as np
from matplotlib import pyplot as plt

from __future__ import print_function
import tensorflow as tf
import keras
from keras.models import Sequential, load_model
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K
from mnist import MNIST
from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split
# print(1)
# image = cv2.imread('3.png')
# print(image.shape)
# # img = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
# cv2.imshow('Original image', image)
# cv2.waitKey(0)

ls

pwd

import os
cwd = os.getcwd()
print(cwd)

batch_size = 128
num_classes = 26
epochs = 10

# Input image dimensions
img_rows, img_cols = 28, 28

emnist_data = MNIST(path='./data/mnist/', return_type='numpy')
emnist_data.select_emnist('byclass')

X, y = emnist_data.load_training()
print(X.shape)
X = X.reshape(124800, 28,28)
y = y.reshape(124800, 1)
y = y - 1

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=111)

x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
input_shape = (img_rows, img_cols, 1)

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')

# Rescale the image values to [0, 1]
x_train = x_train / 255
x_test = x_test / 255

# Convert class vectors to binary class matrices
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

# Set the CNN Architecture
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=input_shape))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))


# Comple the model
model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.Adadelta(),
              metrics=['accuracy'])

# Train the model
model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(x_test, y_test))
# Save the model weights for future reference
# model.save('emnist_cnn_modeld.h5')
model = load_model('emnist_cnn_model.h5')

# Evaluate the model using Accuracy and Loss
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

# image = cv2.imread('F.png')
image = cv2.imread('new160.jpg')
resized_image = cv2.resize(image, (28, 28))
plt.imshow(resized_image)
img = cv2.cvtColor(resized_image, cv2.COLOR_BGR2GRAY)
# # print(img.shape)
for i in range(28):
   for j in range(28):
      temp = 255 - img[i][j]
      img[i][j] = temp
plt.imshow(img)
a = np.asarray(img)
a = a.reshape(1, 28, 28, 1)
print(a.shape)
# plt.imshow(a)
model = load_model('emnist_cnn_model.h5')
model.predict(a, batch_size=16, verbose=0, steps=None)
# # print(image.shape)
# # img = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
# cv2.imshow('Original image', image)
# cv2.waitKey(0)

